### ISSUE TITLE
As a customer I want to view a browse all Recipe's Page so that I can see a  catalogue of recipes I could make.

### ISSUE THREAD

**Issue by kekizl** [AgileGroup6/Agile-Project#201]
# Description of issue

Adds page in which the customer can browse a list of recipes. 

# Tasks
- [x] Create page to view all recipes and add routing from home page.
- [x] Create card component for each recipe.
- [x] Populate card components with backend API.
- [x] Add relevant link to each card component.
# Definition of done
- [x] Requirements for this issue to be marked as completed
- [x] Follows the colour scheme
- [x] Code is well commented
- [x] Tests have been completed
- [x] Run `npm run build` after front end changes
