### ISSUE TITLE
As a customer I would like a navbar button so that I can navigate from different pages effectively.

### ISSUE THREAD

**Issue by benduguid** [AgileGroup6/Agile-Project#213]
# Description of issue

- Adds navbar button for easier navigation between pages.

# Tasks
- [x] Create new vue component for navbar icon.
- [x] Style component.
- [x] Connect component to script.
- [x] Import component to App.vue to be displayed on all pages.

# Definition of done
- [x] Requirements for this issue to be marked as completed
- [x] Follows the colour scheme
- [x] Code is well commented
- [x] Tests have been completed
- [x] Run `npm run build` after front end changes

**Comment by caydey** [comment]
Closed by #266
