### ISSUE TITLE
As a store owner I would like to add recipes to the app so that my customers can try new recipes 

### ISSUE THREAD

**Issue by davidtopping02** [AgileGroup6/Agile-Project#221]
# Description of issue
have a page to add recipes to the db that can then be used by the user

# Definition of done
- [ ] Requirements for this issue to be marked as completed
- [ ] Follows the colour scheme
- [ ] Code is well commented
- [ ] Tests have been completed
- [ ] Run `npm run build` after front end changes

# tasks

- [x] #238
- [ ] #239
- [x] #240

**Comment by davidtopping02** [comment]
completed but not closed by story owners
