### ISSUE TITLE
As a user I want a shareable link so that I can share recipes to others

### ISSUE THREAD

**Issue by ElliotScott0** [AgileGroup6/Agile-Project#26]
# Description of issue
when a recipe is selected the link will change to be specific to that recipe, the link can then be copied

# Tasks
- [x] Edit index.js inside of router to accept unique recipe_id.
- [x] Create function to perform a get request from server to get correct data.
- [x] Create error handling and loading functionality for when a specific recipe is not found.

# Definition of done
- [x] requirements for this issue to be marked as completed
- [x] Follows the colour scheme
- [x] Code is well commented
- [x] Tests have been completed
